name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add VPS to known hosts
      run: ssh-keyscan -H 209.126.3.236 >> ~/.ssh/known_hosts

    - name: Debug SSH Connection
      run: |
        ls -l ~/.ssh
        cat ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no subic@209.126.3.236 'echo "SSH connection successful"'

    - name: Deploy to VPS
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no subic@209.126.3.236 'cd /public_html/subic && git pull origin main && composer install && php artisan migrate'
