name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_PRIVATE_KEY }}" | tr -d '\r' > cat ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add VPS to known hosts
      run: ssh-keyscan -H 209.126.3.236 >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no subic@209.126.3.236 'cd /public_html/subic && git pull origin master && composer install && php artisan migrate'
